# image: node:16  # Specifies the Node.js version to use

# pipelines:
#   default:
#     - step:
#         name: Deploy
#         script:
#           - echo "Starting deployment"
#           - npm install -g pm2  # Installs PM2 globally
#           - npm install  # Installs project dependencies
#           - ls -alh
#           - pm2 restart my-app || pm2 start server.js --name "my-app"  # Restarts or starts the application with PM2

image: atlassian/default-image:2

pipelines:
  branches:
    main:
      - step:
          name: Build and Deploy to EC2
          script:
            - echo "Starting Build and Deploy Step"
            # Install dependencies
            - apt-get update
            - apt-get install -y zip  # Install zip to package application
            - npm install -g pm2     # Install PM2 globally via npm
            - npm install            # Install Node.js dependencies

            # Create a zip file of the application
            - zip -r application.zip .

            # Upload to S3 for deployment
            - pipe: atlassian/aws-code-deploy:0.2.5
              variables:
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                APPLICATION_NAME: $APPLICATION_NAME
                S3_BUCKET: $S3_BUCKET
                COMMAND: 'upload'
                ZIP_FILE: 'application.zip'
                VERSION_LABEL: 'latest-version'

            # Deploy application using CodeDeploy
            - pipe: atlassian/aws-code-deploy:0.2.5
              variables:
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                APPLICATION_NAME: $APPLICATION_NAME
                DEPLOYMENT_GROUP: $DEPLOYMENT_GROUP
                S3_BUCKET: $S3_BUCKET
                COMMAND: 'deploy'
                WAIT: 'true'
                VERSION_LABEL: 'latest-version'
                IGNORE_APPLICATION_STOP_FAILURES: 'true'
                FILE_EXISTS_BEHAVIOR: 'OVERWRITE'

            # Start application with PM2 on designated port
            - pm2 start /var/www/html/server.js --name "my-app" --watch --env production
            - pm2 save  # Saves the PM2 process list to restart on reboot
            - pm2 startup  # Sets up PM2 to restart on system reboot
