pipelines:
  branches:
    develop:
      - step:
          name: Deploy to Desktop
          script:
            - echo "Starting deployment"
            - git pull origin main
            - npm install
            - pm2 restart my-app || pm2 start app.js --name "my-app"
