image: node:16

pipelines:
  default:
    - step:
        name: Deploy
        script:
          - echo "Starting deployment"
          - npm install
          - pm2 restart my-app || pm2 start app.js --name "my-app"
